name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: OS Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          wget https://github.com/tenstorrent/tt-metal/actions/runs/9278790765/artifacts/1546545605
          unzip eager-dist-ubuntu-20.04-wormhole_b0.zip
          pip install metal_libs-0.48.0rc20+wormhole.b0-cp38-cp38-linux_x86_64.whl
      - name: Build documentation
        run: |
          python build_docs.py
      
      - name: Make root index.html
        run: |
          touch output/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output/
          force_orphan: true